// Generated by gencpp from file delbono_kobra/Ptz.msg
// DO NOT EDIT!


#ifndef DELBONO_KOBRA_MESSAGE_PTZ_H
#define DELBONO_KOBRA_MESSAGE_PTZ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delbono_kobra
{
template <class ContainerAllocator>
struct Ptz_
{
  typedef Ptz_<ContainerAllocator> Type;

  Ptz_()
    : p(0.0)
    , t(0.0)
    , z(0.0)  {
    }
  Ptz_(const ContainerAllocator& _alloc)
    : p(0.0)
    , t(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _p_type;
  _p_type p;

   typedef float _t_type;
  _t_type t;

   typedef float _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::delbono_kobra::Ptz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delbono_kobra::Ptz_<ContainerAllocator> const> ConstPtr;

}; // struct Ptz_

typedef ::delbono_kobra::Ptz_<std::allocator<void> > Ptz;

typedef boost::shared_ptr< ::delbono_kobra::Ptz > PtzPtr;
typedef boost::shared_ptr< ::delbono_kobra::Ptz const> PtzConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delbono_kobra::Ptz_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delbono_kobra::Ptz_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delbono_kobra

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'delbono_kobra': ['/home/alex/delbono_catkin_ws/src/delbono_kobra/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delbono_kobra::Ptz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delbono_kobra::Ptz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delbono_kobra::Ptz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delbono_kobra::Ptz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delbono_kobra::Ptz_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delbono_kobra::Ptz_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delbono_kobra::Ptz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d67c83f522ade3e3af5cf25a4c6fe96";
  }

  static const char* value(const ::delbono_kobra::Ptz_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d67c83f522ade3eULL;
  static const uint64_t static_value2 = 0x3af5cf25a4c6fe96ULL;
};

template<class ContainerAllocator>
struct DataType< ::delbono_kobra::Ptz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delbono_kobra/Ptz";
  }

  static const char* value(const ::delbono_kobra::Ptz_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delbono_kobra::Ptz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 p\n\
float32 t\n\
float32 z\n\
";
  }

  static const char* value(const ::delbono_kobra::Ptz_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delbono_kobra::Ptz_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
      stream.next(m.t);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Ptz_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delbono_kobra::Ptz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delbono_kobra::Ptz_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "t: ";
    Printer<float>::stream(s, indent + "  ", v.t);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELBONO_KOBRA_MESSAGE_PTZ_H
